#décrit tous les “services” à démarrer (app, nginx, mysql, redis…)
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestion_reservation-app
    container_name: gestion_reservation-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=reservation
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - REDIS_HOST=redis

  nginx:
    image: nginx:alpine
    container_name: gestion_reservation-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: gestion_reservation-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: gestion_reservation-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge